//! Crate-level error types

use std::error;
use std::ffi::NulError;
use std::fmt;
use std::option::NoneError;

/// Crate `Error` type
#[derive(Debug)]
pub enum Error {
    /// Errors related to argument handling
    Arg { reason: &'static str },
    /// Errors related to parsing data
    Parse { err: Box<dyn error::Error> },
    /// Errors generated by OS functions
    OS { err: Box<dyn error::Error> },
    /// Errors from unwrapping bad strings
    String { reason: &'static str },
}

/// Crate `Result` type
pub type Result<T> = std::result::Result<T, Error>;

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        use self::Error::*;
        match self {
            Arg { reason } => write!(f, "Arg: {}", reason),
            Parse { err } => write!(f, "Parse: {}", err),
            OS { err } => write!(f, "OS: {}", err),
            String { reason } => write!(f, "String: {}", reason),
        }
    }
}

impl error::Error for Error {
    fn source(&self) -> Option<&(dyn error::Error + 'static)> {
        // TODO: Fix this (although I don't think it matters)
        None
    }
}

impl From<NulError> for Error {
    fn from(_err: NulError) -> Self {
        Error::Arg {
            reason: "Null character in argument",
        }
    }
}

impl From<NoneError> for Error {
    fn from(_err: NoneError) -> Self {
        Error::String {
            reason: "Unable to convert to string",
        }
    }
}

impl From<nix::Error> for Error {
    fn from(err: nix::Error) -> Self {
        Error::OS { err: err.into() }
    }
}

impl From<std::str::Utf8Error> for Error {
    fn from(err: std::str::Utf8Error) -> Self {
        Error::Parse { err: err.into() }
    }
}
